# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'SwiftDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    #swift
	pod 'SnapKit', '5.0.1'
       #pod 'Kingfisher', '5.10.0'
	#pod 'IQKeyboardManagerSwift', '6.5.4'
       #pod 'SwiftyJSON', '5.0.0'
	#pod 'Moya', '14.0.0-beta.5'
	#pod 'HandyJSON', '5.0.1'
	#pod 'SDCycleScrollView', '1.80'
       #pod 'Result', '5.0.0'
 #OC
	pod 'WMPageController', '2.5.2'
	pod 'MBProgressHUD', '1.1.0'
	pod 'MJRefresh', '3.2.2'
	pod 'XHLaunchAd', '3.9.8'
	pod 'TZImagePickerController', '3.2.7'

  # Pods for SwiftDemoProject

end
